In [1]:
import numpy as np

In [2]:
# 2차원 행렬 만들기기
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [4]:
# 랜덤한 숫자로 행렬 만들기
C = np.random.rand(3, 5)

C

array([[0.86154293, 0.82112612, 0.39700031, 0.37079523, 0.21239832],
       [0.37003591, 0.89307825, 0.53190834, 0.24811971, 0.56824635],
       [0.12571927, 0.64333771, 0.12980246, 0.5805533 , 0.85336872]])

In [5]:
# 모든 값이 0인 행렬 만들기 - 괄호를 두 번!
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# 원소 받아오기
# A[1][3]  # 0행 4열의 값을 출력
A[0][2]  # 1행 3열의 값을 출력

2