### 행렬의 덧셈과 곱셈
덧셈: 같은 위치의 값 끼리 더함.  
* 행렬을 더하기 위해서는 두 행렬의 차원(행과 열의 수)가 같아야 한다.  

곱셈
1) 스칼라 곱: 행렬과 상수(스칼라)를 곱함  
- 행렬의 각 원소에 상수를 곱한 값이 결과.  
2) 행렬곱셈 - 내적곱  
- A = [1 3 1]   B = [5 6]  
      [2 2 1]       [4 2]  
                    [3 1]  
-> A의 1행과 B의 1열을 곱셈 (1x5 + 3x4 + 1x3) = 20(1행 1열)  
-> A의 1행과 B의 2열을 곱셈 -> 1행 2열  
-> A의 2행과 B의 1열을 곱셈 -> 2행 1열  
-> A의 2행과 B의 2열을 곱셈 (2x6 + 2x2 + 1x1) -> 2행 2열  
A X B = [20 13]  
        [21 17]  
A가 행을, B가 열을 제공 -> A의 열과 B의 행 수가 같아야 곱할 수 있다.  
m x n 행렬과 n x p 행렬을 곱하면 m x p 행렬이 결과로 나온다.

In [1]:
import numpy as np

In [3]:
A = np.array([[1, -1, 2],
              [3, 2, 2],
              [4, 1, 2]])
B = np.random.rand(3, 3)

In [4]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
B

array([[0.56445175, 0.63919569, 0.34496469],
       [0.68916011, 0.79553205, 0.53979304],
       [0.77938086, 0.52167807, 0.71591883]])

In [6]:
A + B

array([[ 1.56445175, -0.36080431,  2.34496469],
       [ 3.68916011,  2.79553205,  2.53979304],
       [ 4.77938086,  1.52167807,  2.71591883]])

In [7]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
# 행렬 곱
np.dot(A, B)

array([[1.43405335, 0.88701977, 1.23700932],
       [4.63043718, 4.5520073 , 3.54631781],
       [4.50572882, 4.39567093, 3.35148946]])

In [9]:
# 행렬 곱 다른 방법 (간단!)
A @ B

array([[1.43405335, 0.88701977, 1.23700932],
       [4.63043718, 4.5520073 , 3.54631781],
       [4.50572882, 4.39567093, 3.35148946]])

In [10]:
A @ B + (A + 2 * B)

array([[ 3.56295685,  1.16541114,  3.92693869],
       [ 9.00875741,  8.1430714 ,  6.62590389],
       [10.06449054,  6.43902707,  6.78332712]])