- 전치행렬(T) : 기존 행의 행과 열의 위치를 바꾼 것. (2행3열 -> 3행2열) A^T로 표기함.  
    - 기존 행렬로 행렬곱을 연산할 때 행렬 개수가 안 맞으면 전치행렬을 사용하기도 함.  

- 단위행렬(identity matrix, I) : 0과 1로만 이루어진 행렬, 항상 정사각형-행과 열의 수가 동일해야 함. (3행3열, 4행4열, ...)  
    - 일반행렬과 단위행렬을 곱하면 일반행렬과 동일한 값이 나온다.  
    - 어떤 수에 상수 1을 곱하면 자기 자신이 나오는 것과 같은 역할.

- 역행렬 : 일반행렬에 어떠한 행렬을 곱했을 때 단위행렬이 나오도록 하는 행렬. (A x ? = I) -> A^-1으로 표기함.
    - 역행렬은 항상 정사각형
    - 모든 행렬에 역행렬이 존재하는 것은 아님.

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
# 전치행렬 만들기
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [7]:
# 전치행렬 만들기 2
A_transpose2 = A.T
A_transpose2

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [8]:
# 단위행렬 만들기
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
A @ I  # 기존 행렬 A와 동일한 행렬이 출력됨.

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [12]:
# 역행렬
A_inverse = np.linalg.pinv(A)  # .pinv() 메서드는 역행렬이 없는 경우 최대한 비슷한 효과를 내는 행렬을 리턴함.
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [13]:
# 역행렬이 제대로 나왔는지 확인
A @ A_inverse  # 단위행렬이 출력되면 맞게 나온 것.

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 2.22044605e-16,  2.22044605e-16,  1.00000000e+00]])